/*
 * Description: Shared widget types — used by both editor and viewer.
 *
 * Author: xiaoyown
 * Created: 2026-03-26
 */

import type { WidgetRaw, WidgetRuntime } from '@canvix-react/schema-widget';
import type { ComponentType } from 'react';

// ── Widget Plugin Definition ───────────────────────────────────────────────

export interface WidgetPluginDefinition<T = unknown> {
  /** Widget type identifier, globally unique. */
  type: string;
  /** Metadata (name, category, icon, description). */
  meta: WidgetMeta;
  /** Default custom data. */
  defaultCustomData: T;
  /** Full default schema (optional, generated by defaults() if omitted). */
  defaultSchema?: WidgetRaw<T>;
  /** Render components (editor + viewer). */
  render: WidgetRenderMap;
  /** Slot declarations (optional, allows child widgets). */
  slots?: WidgetSlot[];
}

export interface WidgetMeta {
  name: string;
  category: string;
  icon: ComponentType<{ size?: number; className?: string }>;
  description?: string;
}

export interface WidgetRenderProps<T = unknown> {
  /** Complete widget runtime data. */
  widget: WidgetRuntime<T>;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export interface WidgetRenderMap {
  editor: ComponentType<WidgetRenderProps<any>>;
  viewer: ComponentType<WidgetRenderProps<any>>;
}

// ── Widget Slot ────────────────────────────────────────────────────────────

export interface SlotAcceptContext {
  /** The widget that owns this slot. */
  owner: WidgetRuntime;
  /** The widget(s) about to be inserted into the slot. */
  incoming: WidgetRuntime[];
}

export interface WidgetSlot {
  name: string;
  label: string;
  /** Validation function — return true to accept. Omit to accept all. */
  accept?: (ctx: SlotAcceptContext) => boolean;
}

// ── Widget Registry ────────────────────────────────────────────────────────

export interface WidgetRegistry {
  register(definition: WidgetPluginDefinition): void;
  registerAll(definitions: WidgetPluginDefinition[]): void;
  get(type: string): WidgetPluginDefinition | undefined;
  getAll(): WidgetPluginDefinition[];
  getByCategory(category: string): WidgetPluginDefinition[];
  has(type: string): boolean;
}
