/*
 * Description: Widget plugin types — definition, inspector, slots, registry.
 *
 * Author: xiaoyown
 * Created: 2026-03-26
 */

import type { WidgetRaw, WidgetRuntime } from '@canvix-react/schema-widget';
import type { ComponentType } from 'react';

// ── Widget Plugin Definition ───────────────────────────────────────────────

export interface WidgetPluginDefinition<T = unknown> {
  /** Widget type identifier, globally unique. */
  type: string;
  /** Metadata (name, category, icon, description). */
  meta: WidgetMeta;
  /** Default custom data. */
  defaultCustomData: T;
  /** Full default schema (optional, generated by defaults() if omitted). */
  defaultSchema?: WidgetRaw<T>;
  /** Render components (editor + viewer). */
  render: WidgetRenderMap;
  /** Inspector panel definition (optional). */
  inspector?: WidgetInspectorConfig;
  /** Slot declarations (optional, allows child widgets). */
  slots?: WidgetSlot[];
}

export interface WidgetMeta {
  name: string;
  category: string;
  icon: ComponentType<{ size?: number; className?: string }>;
  description?: string;
}

export interface WidgetRenderProps<T = unknown> {
  data: T;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export interface WidgetRenderMap {
  editor: ComponentType<WidgetRenderProps<any>>;
  viewer: ComponentType<WidgetRenderProps<any>>;
}

// ── Inspector ──────────────────────────────────────────────────────────────

export type Chain = (string | number)[];

export type UpdateField = (chain: Chain, value: unknown) => void;

export interface InspectorField {
  chain: Chain;
  renderer: string;
  label: string;
  span?: 1 | 2 | 3 | 4;
  options?: Record<string, unknown>;
}

export interface InspectorGroup {
  title: string;
  properties: InspectorField[];
}

export interface WidgetInspectorConfig {
  render: (data: WidgetRuntime) => InspectorGroup[];
}

// ── Widget Slot ────────────────────────────────────────────────────────────

export interface WidgetSlot {
  name: string;
  label: string;
  accept?: string[];
  maxCount?: number;
}

// ── Widget Registry ────────────────────────────────────────────────────────

export interface WidgetRegistry {
  register(definition: WidgetPluginDefinition): void;
  registerAll(definitions: WidgetPluginDefinition[]): void;
  get(type: string): WidgetPluginDefinition | undefined;
  getAll(): WidgetPluginDefinition[];
  getByCategory(category: string): WidgetPluginDefinition[];
  has(type: string): boolean;
}
